name=AdafruitADA5752
version=1.0.0
author=mumanchu
maintainer=mumanchu <info@muman.ch>
sentence=Library for the Adafruit ADA5752 I2C Quad Rotary Encoder with 4 x Neopixel LEDs
paragraph=PRELIMINARY
category=Device Control
includes=AdafruitADA5752.h
url=https://github.com/mumanchu/AdafruitADA5752
architectures=*

